### ISSUE TITLE
[Wiki]Add docker-compose .yml launch config

### ISSUE THREAD

**Issue by sethidden** [DuckBoss/JJMumbleBot#339]
## Post any issues with the wiki here -
This may include:
- Out of date content on the wiki,
- Incorrect information on the wiki.
- Any request to add information to the wiki.

It'd be nice to add docker-compose **.yml** to https://duckboss.github.io/JJMumbleBot/wiki/general/docker.html

There's already the below snippet:
```
Minimal run command using docker-compose (with environment variables for IP/Port/Password):
sudo -E docker-compose run -e MUMBLE_IP -e MUMBLE_PORT -e MUMBLE_PASSWORD bot -generatecert -username 'bot_username' -superuser 'superuser_username'
Minimal run command using docker-compose (no environment variables):
sudo docker-compose run bot -generatecert -ip 'server_ip' -port 'server_port' -username 'bot_username' -superuser 'superuser_username'
```

But I think most people use the docker-compose with a docker-compose.yml file where they have other services like Nextcloud, Jellyfin etc and the docs don't provide a snippet that can be included in a docker-compose.yml file

I actually made one that works for me (please if someone can test):

```yml
version: "3.5"
  services:
    jjmumblebot:
      image: jasonjerome/jjmumblebot
      network_mode: host
      command: -generatecert -ip 'server_ip'  -port 'server_port' -username 'bot_username' -superuser 'superuser_username'
```
I think it's important to add the .yml file. One could say its trivial to create a docker-compose.yml file based on the docker run command from the docs using eg. www.composerize.com but that website doesn't understand the stuff that's in the `command:` property above and returns 'true'

Plus it's the first time I actually see `-generatecert` etc. launch commands being used :P
